In [2]:
import statistics
import pandas as pd
import numpy as np
from scipy import stats

In [1]:
beras = 11400
minyak = 12700
ayam = 3400
telur = 21800
popok = 27000
sabun = 1800
anggur = 3800
roti = 8500
tissu = 6400 
mie = 2200
print("=== belanjaan tia ===") 
beras_tia = 4
ayam_tia = 20
telur_tia = 3
sabun_tia = 5
anggur_tia = 4
roti_tia = 2
mie_tia = 12
jb_tia = (beras_tia * beras) + (ayam_tia * ayam ) + (telur_tia * telur) + (sabun_tia * sabun) + (anggur_tia * anggur) + (roti_tia * roti) + (mie_tia * mie)
diskon = 80
jb_diskon_tia = (jb_tia / 100) * diskon
print("maka belajaan tia " + str(jb_tia) + "rupiah")
print("maka jumlah belanjaan tia setelah mendatpatkan diskon adalah " + str(jb_diskon_tia))

print("===belanjaan hana===")
minyak_hana = 2
ayam_hana = 5
telur_hana = 1.5
sabun_hana = 3
anggur_hana = 8
roti_hana = 3
tissu_hana = 2
mie_hana = 20
jb_hana = (minyak_hana * minyak) + (ayam_hana * ayam ) + (telur_hana * telur) + (sabun_hana * sabun) + (anggur_hana * anggur) + (roti_hana * roti) + (tissu_hana * tissu) + (mie_hana * mie)
print("maka belajaan hana " + str(jb_hana) + "rupiah")


print("===belanjaan widia===")
beras_widia = 1
minyak_widia = 1
telur_widia = 1
anggur_widia = 5
tissu_widia = 3
mie_widia = 16
jb_widia = (beras_widia * beras) + (minyak_widia * minyak) + (telur_widia * telur) + (anggur_widia * anggur) + (tissu_widia * tissu) + (mie_widia* mie)
print("maka belajaan widia " + str(jb_widia) + "rupiah")

print("===belanjaan samsul===")
ayam_samsul = 3
telur_samsul= 4
popok_samsul= 2
anggur_samsul= 7
tissu_samsul= 5
mie_samsul= 10
jb_samsul =  (ayam_samsul * (ayam * 10)) + (telur_samsul * telur) + (popok_samsul * popok) + (anggur_samsul * anggur) +  (tissu_samsul * tissu) + (mie_samsul * mie)
print("maka belajaan samsul " + str(jb_samsul) + "rupiah")


print("===belanjaan romi===")
minyak_romi = 3
telur_romi = 2
popok_romi = 4
sabun_romi = 8
mie_romi = 8
jb_romi =  (minyak_romi * minyak ) + (telur_romi * telur) + (popok_romi * popok) + (sabun_romi * sabun) + (mie_romi* mie)
print("maka belajaan romi " + str(jb_romi) + "rupiah")

print("===belanjaan dimas===")
ayam_dimas = 5
popok_dimas = 5
sabun_dimas = 4
anggur_dimas = 3
roti_dimas = 5
mie_dimas = 6
jb_dimas =  (ayam_dimas * ( ayam * 10 )) + (popok_dimas * popok) + (sabun_dimas * sabun) +  (anggur_dimas * anggur) +  (roti_dimas * roti) + (mie_dimas* mie)
print("maka belajaan dimas " + str(jb_dimas) + "rupiah")

print("===soal 2====")
diskon = 80
jb_diskon_tia = (jb_tia / 100) * diskon
print("maka jumlah belanjaan tia setelah mendatpatkan diskon adalah " + str(jb_diskon_tia))

diskon = 85
jb_diskon_hana = (jb_hana / 100) * diskon
print("maka jumlah belanjaan hana setelah mendatpatkan diskon adalah " + str(jb_diskon_hana))

diskon = 90
jb_diskon_widia = (jb_widia / 100) * diskon
print("maka jumlah belanjaan widia setelah mendatpatkan diskon adalah " + str(jb_diskon_widia))

diskon = 80
jb_diskon_romi = (jb_romi / 100) * diskon
print("maka jumlah belanjaan romi setelah mendatpatkan diskon adalah " + str(jb_diskon_romi))

diskon = 75
jb_diskon_samsul = (jb_samsul / 100) * diskon
print("maka jumlah belanjaan samsul setelah mendatpatkan diskon adalah " + str(jb_diskon_samsul))

diskon = 75
jb_diskon_dimas = (jb_dimas / 100) * diskon
print("maka jumlah belanjaan dimas setelah mendatpatkan diskon adalah " + str (jb_diskon_dimas))


print("===soal 3====")
max = [284475]
print("maka jumlah belanjaan yang paling besar setelah diskon adalah diskon dimas rp." + str(max))



tenpersen = {"hana" : "rp.173880"}
print("maka yang mendapatkan diskon 10persen adalah " + str(tenpersen))

=== belanjaan tia ===
maka belajaan tia 246600rupiah
maka jumlah belanjaan tia setelah mendatpatkan diskon adalah 197280.0
===belanjaan hana===
maka belajaan hana 193200.0rupiah
===belanjaan widia===
maka belajaan widia 119300rupiah
===belanjaan samsul===
maka belajaan samsul 323800rupiah
===belanjaan romi===
maka belajaan romi 221700rupiah
===belanjaan dimas===
maka belajaan dimas 379300rupiah
===soal 2====
maka jumlah belanjaan tia setelah mendatpatkan diskon adalah 197280.0
maka jumlah belanjaan hana setelah mendatpatkan diskon adalah 164220.0
maka jumlah belanjaan widia setelah mendatpatkan diskon adalah 107370.0
maka jumlah belanjaan romi setelah mendatpatkan diskon adalah 177360.0
maka jumlah belanjaan samsul setelah mendatpatkan diskon adalah 242850.0
maka jumlah belanjaan dimas setelah mendatpatkan diskon adalah 284475.0
===soal 3====
maka jumlah belanjaan yang paling besar setelah diskon adalah diskon dimas rp.[284475]
maka yang mendapatkan diskon 10persen adalah {'hana': 'rp.173880'}